blog_app/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/',views.index,name="index"),
    path('post/<str:slug>',views.detail,name="detail"),
    path("old_url/",views.old_url_redirect,name="old_url"),
    path("new_url/",views.new_url_redirect,name="new_url"),
    path('contact/',views.contact,name="contact"),
    path('aboutus/',views.about,name='about_us'),
    path('register/',views.register,name="register"),
    path('login/',views.login,name="login"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('logout/',views.logout,name="logout"),
    path('forget_password/',views.forget_password,name="forget_password"),

]

blog_app/blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from blog import urls

handler404= "blog_app.views.coustom_errorpage"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls'),name="blog")
]

blog_app/blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils.text import slugify


# Create your models here.

# Catagory model

class Catagory(models.Model):
    #catagories = ["Food", "Artificial Intelligence", "Data Science", "Games", "Sports"]
    catagories = models.CharField(max_length=100)

    def __str__(self):
        return self.catagories

#post Model

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image_url = models.URLField(null=True)
    created_at_time = models.DateTimeField(auto_now_add=True)
    slugs = models.SlugField(unique=True)
    catagory = models.ForeignKey(Catagory,on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.slugs = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
class AboutUS(models.Model):
    content = models.TextField()
    def __str__(self):
        return self.content

blog_app/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class ContactDetail(forms.Form):
    name = forms.CharField(label='Name',max_length=100, required=True)
    email = forms.EmailField(label="Email", required=True)
    message = forms.CharField(label="Message", required=False)

class RegisterForms(forms.ModelForm):
    username = forms.CharField(label="Username",max_length=15, required=True)
    email = forms.EmailField(label="Email",max_length=50, required=True)
    password = forms.CharField(label="Password",min_length=8,max_length=20, required=True)
    password_confirm = forms.CharField(label="Confirm password",min_length=8,max_length=20,required=True)
    

    class Meta:
        model = User
        fields = ['username','email','password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("The password doesn't match")
        
class LoginForm(forms.Form):
    username = forms.CharField(label="User name",max_length=30,required=True)
    password = forms.CharField(label="Password",min_length=8,max_length=20,required=True)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username,password=password)
            
            if user is None:
                raise forms.ValidationError("Invalid username or password")

blog_app/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404
from django.urls import reverse
import logging
from django.core.paginator import Paginator
from .models import Post,Catagory,AboutUS
from .forms import ContactDetail,RegisterForms,LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout

# Create your views here.
#posts=[
#        {"id":1,"title":"Post-1","content":"Content of post 1"},
#       {"id":2,"title":"Post-2","content":"Content of post 2"},
#       {"id":3,"title":"Post-3","content":"Content of post 3"},
#       {"id":4,"title":"Post-4","content":"Content of post 4"},
#   ]

all_posts= Post.objects.all()
catagories = Catagory.objects.all()


def index(request):
    title='Latest posts'

    paginator = Paginator(all_posts,6)
    page_no = request.GET.get("page")
    page_obj = paginator.get_page(page_no)

    return render(request,"blog/index.html",{"title":title,"page_obj":page_obj,"Catagories":catagories})

def detail(request,slug):
    #post=next((item for item in posts if item["id"] == int(post_id)),None)
    
    try:

        post=Post.objects.get(slugs=slug)
        related_posts = Post.objects.filter(catagory_id=post.catagory_id).exclude(pk= post.catagory_id)

    except Post.DoesNotExist:
        raise Http404("Post Does not found")

    
    return render(request,"blog/detail.html",{"post":post,"related_posts":related_posts,"Catagories":catagories})

def old_url_redirect(request):
    return redirect(reverse("blog:new_url"))

def new_url_redirect(request):
    return HttpResponse("Redirected url")

def contact(request):
    form = ContactDetail()
    if request.method == 'POST':
        form = ContactDetail(request.POST)
        if form.is_valid():
            messages.success(request,"Your responce has been recorded")
            #logger=logging.getLogger("TESTING")
            #logger.debug(f"name = {form.cleaned_data['name']} email = {form.cleaned_data['email']} message = {form.cleaned_data['message']}")
    return render(request,"blog/contact.html",{'title':'Contact us','form':form})

def about(request):
    about_content = AboutUS.objects.first()
    if about_content is None or not about_content.content:
        about_content = "This content is currently unavailable"
    else:
        about_content = about_content.content
    return render(request,"blog/about.html",{'about_content':about_content,'title':'About us'})

def register(request):
    form = RegisterForms()
    if request.method == 'POST':
        form = RegisterForms(request.POST)
        if form.is_valid():
            user_data=form.save(commit=False)
            user_data.set_password(form.cleaned_data['password'])
            user_data.save()
            messages.success(request,"You have successfully registered! Now you can Log in")
            return redirect(reverse('blog:login'))
    return render(request,"blog/register.html",{'form':form,'title':'Register'})

def login(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                auth_login(request,user)
                return redirect(reverse("blog:dashboard"))
    return render(request,'blog/login.html',{'title':'Log in','form':form})

def dashboard(request):
    return render(request,"blog/dashboard.html",{'title':'dashboard'})

def logout(request):
    auth_logout(request)
    return redirect(reverse("blog:index"))

def forget_password(request):
    return render(request,"blog/forget_password.html",{'title':'Forget Password'})

blog_app/blog_app/views.py
from django.shortcuts import render

def coustom_errorpage(request,exception):
    return render(request,"404.html",status=404)

blog_app/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
                {{about_content}}
            </div>
        </div>
    </div>
{% endblock content %}

blog_app/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}{{post.title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <!-- Header -->
    {% include "blog/includes/header.html" %}
    
    {% block content %}

    {% endblock content %}

    <!-- Footer -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% include "blog/includes/footer.html" %}
</body>
</html>

blog_app/blog/templates/blog/contact.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container-fluid ">
    <div class="d-flex justify-content-center mt-5">
        <div class="d-flex gap-3 flex-column">
            <h3>Contact Form</h3>
            <form method="post" class="row g-3">
                {% csrf_token %}
                <div class="col-md-6">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{form.name.value |default:''}}">
                    {% if form.name.errors %}
                        <div class="col-12">
                            <span class="text-danger">{{form.name.errors}}</span>
                        </div>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{form.email.value |default:''}}">
                    {% if form.email.errors %}
                        <div class="col-12">
                            <span class="text-danger">{{form.email.errors}}</span>
                        </div>
                    {% endif %}

                </div>
                <div class="col-12">
                    <label for="message" class="form-label">Message</label>
                    <textarea class="form-control" id="message" name="message" rows="4" ></textarea>
                    {% if form.message.errors %}
                        <div class="col-12">
                            <span class="text-danger">{{form.message.errors}}</span>
                        </div>
                    {% endif %}

                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div> 
</div>
<div class="text-center">
    {% if messages %}
        {% for sucess_message in messages %}
            <div class="alert alert-success" role="alert">{{sucess_message}}</div>
        {% endfor %}
    {% endif %}
</div>
{% endblock content %}

blog_app/blog/templates/blog/dashboard.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container-fluid ">
        <div class="row">
          <div class="col-6">
              <h3> Hi, [USERNAME].</h3>
          </div>
          <div class="col d-flex justify-content-end">
              <div>
                  <h2>Your Groups:</h2>
                  <ul>
                      <li>[GROUP NAME]</li>
                      <li>You are not a member of any groups.</li>
                  </ul>
              </div>
          </div>
        </div>
        <div class="row d-flex justify-content-center">
          <div class="col-6">
              [ERRORS]
          </div>
        </div>
        <div class="row">
          <h2 class="mt-3">[TITLE]</h2>
          <div class="d-flex justify-content-center">
              <a href="/newpost" class="btn btn-success">New Post</a>
          </div>
        </div>
        <div class="row m-3">
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height:300; width:300;" src="https://placehold.co/600x400" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">[POST TITLE]</h5>
                                <p class="card-text">[POST CONTENT]</p>
                                <div class="d-flex justify-content-between">
                                    <a href="[POST DETAIL URL]">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">[CATEGORY NAME]</a>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex justify-content-between mt-3">
                          <a class="btn btn-info btn-sm text-light" href="[EDIT POST URL]">Edit Post</a>
                          <a class="btn btn-danger btn-sm text-light" href="[DELETE POST URL]">Delete Post</a>
                          <a class="btn btn-success btn-sm text-light" href="[PUBLISH POST URL]">Publish Post</a>
                          <label class="text-danger">Not Published</label>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock content %}

blog_app/blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">
                {{post.title}}
                {%for catagory in Catagories%}
                {% if post.catagory_id == catagory.id %}
                <small style="font-size:18px">({{catagory.catagories}})</small>
                {%endif%}
            {%endfor%}
          </h1>
              <p class="text-muted">{{post.created_at |date:"F j, Y"}}</p>
              <img style="height:400; width:800" src="{{post.image_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts%}
                        <li><a href="{% url 'blog:detail' slug=related_post.slugs %}">{{related_post.title}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>
{% endblock content %}

blog_app/blog/templates/blog/forget_password.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row d-flex justify-content-center">
            <div class="col-3 mt-3">
                <h2>Forgot Password</h2>
                <form method="post">
                    <div class="mb-3">
                        <label for="email" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Send Password Reset Email</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

blog_app/blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3 fixed-bottom">
  <div class="row">
      <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2024 Zoro, Inc</span>
      </div>
  </div>
</footer>

blog_app/blog/templates/blog/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="row">
        <div class="col">
            <a class= "text-light text-decoration-none" href="/blog" ><h3>Blog</h3></a>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="{% url 'blog:index' %}">Home</a>
                <a class="text-light text-decoration-none" href="{% url 'blog:about_us' %}">About Us</a>
                <a class="text-light text-decoration-none" href="{% url "blog:contact" %}">Contact</a>
                {% if user.is_authenticated %}
                    <a class="text-light text-decoration-none" href="{% url "blog:dashboard" %}">Dashboard</a>
                    <a class="text-light text-decoration-none" href="{% url "blog:logout" %}">Log out</a>
                {% else %}
                    <a class="text-light text-decoration-none" href="{% url "blog:login" %}">Log in</a>
                    <a class="text-light text-decoration-none" href="{% url "blog:register" %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

blog_app/blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container-fluid ">
            <div class="row my-2">
                <div class="col">
                    <h2 >{{blog_title}}</h2>
                </div>
                <div class="col-3">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                        <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                        <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                        </button>
                    </div>
                </div>
            </div>
            <div class="row m-3">
                {% if page_obj%}
                    {% for post in page_obj%}
                        <div class="col-4 mb-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img style="height:300; width:300" src="{{post.image_url}}" class="img-fluid" alt="...">
                                        </div>
                                        <div class="col-md-8">
                                            <h5 class="card-title">{{post.title}}</h5>
                                            <p class="card-text">{{post.content |truncatechars:30}}</p>
                                            <div class="d-flex justify-content-between">
                                                <a href="{% url "blog:detail" slug=post.slugs %}">Read More</a>
                                                <a class="text-decoration-none text-dark fw-bold" href="#">
                                                    {%for catagory in Catagories%}
                                                        {% if post.catagory_id == catagory.id %}
                                                        {{catagory.catagories}}
                                                        {%endif%}
                                                    {%endfor%}
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor%}
                    <div class="col-12 my-3">
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                <li class="page-item">
                                    {% if page_obj.has_previous %}
                                            <a class="page-link" href="?page=1" aria-label="First">
                                                <span aria-hidden="true">&laquo; first</span>
                                            </a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                                <span aria-hidden="true">previous</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                            <span aria-hidden="true">next</span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                            <span aria-hidden="true">last &raquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                        
                    </div>
                {% else%}
                        <h1>post not found</h1>
                {% endif %}
            </div>
            <div class="row">
            
            </div>
            
    </div>
{% endblock content %}

blog_app/blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Login</h3>
                {% if messages %}
                            {% for message in messages %}
                                <div class= "col-12" >
                                    <div class = "alert alert-success">
                                        <span>{{message}}</span>
                                    </div>
                                </div>
                            {% endfor %}
                {% endif %}
                <div class="">
                    <div class="col-12">
                        <span class="fw-bold"></span>
                        <span class="text-danger"></span>
                    </div>
                </div>
    
                <div class="col-12">
                    <span class="text-danger"></span>
                </div>        
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value |default:''}}">
                            {% if form.username.errors %}
                                {% for error in form.username.errors %}
                                    <div class="col-12">
                                            <span class="text-danger">{{form.username.errors}}</span>
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                       
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                                {% if form.password.errors %}
                                    {% for error in form.password.errors %}
                                        <div class="col-12">
                                                <span class="text-danger">{{form.password.errors}}</span>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                        </div>
                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger" >
                                    <span class="text-danger">{{error}}</span>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="my-3 d-flex justify-content-between">
                            <a href="{% url "blog:forget_password" %}">Forgot Password</a>
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
    

blog_app/blog/templates/blog/register.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                
                <h3>Register</h3>
                <div class="">
                </div>
                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value |default:""}}">
                            {% if form.username.errors %}
                                <div class="col-12">
                                    <span class="text-danger">{{form.username.errors}}</span>
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{form.email.value |default:""}}">
                            {% if form.email.errors %}
                                <div class="col-12">
                                    <span class="text-danger">{{form.email.errors}}</span>
                                </div>
                            {% endif %}

                        </div>
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                            {% if form.password.errors %}
                                <div class="col-12">
                                        <span class="text-danger">{{form.password.errors}}</span>
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="confirm_password" class="form-label">Confirm Password</label>
                            <input type="password" class="form-control" id="confirm_password" name="password_confirm">
                            {% if form.password_confirm.errors %}
                                <div class="col-12">
                                    <span class="text-danger">{{form.password_confirm.errors}}</span>
                                </div>
                            {% endif %}
                        </div>
                        {% for error in form.non_field_errors %}
                            <div class="col-12">
                                <div class = "alert alert-danger">
                                    <span class="text-danger">{{error}}</span>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="my-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">Register</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}